### PR TITLE
Support controller.cancelSecureBootstrapS2

### PR DESCRIPTION
**Pull request by MindFreeze**
Needed for https://github.com/zwave-js/certification-backlog/issues/34

### CODE REVIEW

**Review by MartinHjelmare — COMMENTED** [review]
Please bump the schema version, and update the API docs and readme.

**Comment by MartinHjelmare** [comment]
If we include this with the v14 support before it's released (schema 40) we don't need a schema bump here.

**Comment by MindFreeze** [comment]
Yea, let's get it into 40. I added it to that schema. Don't think README needs anything as it is a straight proxy to the driver and these are not explicitly explained there as far as I can see

**Comment by MartinHjelmare** [comment]
Dominic or Raman should review the code.

**Pull request merged**
