### PR TITLE
Bump zwave-js to 6.5.0

### PR DESCRIPTION
**Pull request by marcelveldt**

### CODE REVIEW

**Comment by marcelveldt** [comment]
we should release 1.0.0 after this one is merged

**Comment by robertsLando** [comment]
Could you release this today? So I can make a new release too

**Review by MartinHjelmare — APPROVED** [review]

**Comment by marcelveldt** [comment]
> Could you release this today? So I can make a new release too

1.0.0 is published but hold on for a second as we're tracing a weird issue with package dependencies

**Comment by marcelveldt** [comment]
@robertsLando maybe it's fine to release. The issue seems to be related by installing the packages in the right order.
See my post in slack about it.

**Comment by robertsLando** [comment]
Just saw it, ok I will go with the release so

**Pull request merged**
