### PR TITLE
Forward ZJS errors

### LINKED ISSUE #209: Handle ZWaveError thrown from driver
As reported in this issue, https://github.com/home-assistant/core/issues/49996, when the driver throws a `ZWaveError` the server returns it to clients as an "`unknown_error"` with no useful information. It would be more helpful to return a descriptive error.

### PR DESCRIPTION
**Pull request by balloob**
Untested. Anyone can test with a real stick?

Fixes #209

CC @raman325 @MartinHjelmare

### CODE REVIEW

**Comment by kpine** [comment]
I made a device fail, and this was the resulting message from the server to the ws client:
```json
{
    "type": "result",
    "success": false,
    "messageId": 1234555,
    "errorCode": "zwave_error",
    "zwave_error_code": 20,
    "zwave_error_message": "Failed to send the command after 3 attempts (Status NoAck)"
}
```
Here is the accompanying stack trace:
```
23:45:31.377 CNTRLR   [Node 007] Node 7 did not respond after 3 attempts, it is presumed dead
23:45:31.378 CNTRLR   [Node 007] The node is now dead.
Z-Wave error ZWaveError: Failed to send the command after 3 attempts (Status NoAck)
    at Driver.sendMessage (/home/keith/src/zwave-js/zwave-js-server/node_modules/zwave-js/src/lib/driver/Driver.ts:2405:23)
    at Driver.sendCommand (/home/keith/src/zwave-js/zwave-js-server/node_modules/zwave-js/src/lib/driver/Driver.ts:2528:28)
    at ThermostatModeCCAPI.set (/home/keith/src/zwave-js/zwave-js-server/node_modules/zwave-js/src/lib/commandclass/ThermostatModeCC.ts:162:21)
    at Proxy.ThermostatModeCCAPI.<computed> (/home/keith/src/zwave-js/zwave-js-server/node_modules/zwave-js/src/lib/commandclass/ThermostatModeCC.ts:96:14)
    at ZWaveNode.setValue (/home/keith/src/zwave-js/zwave-js-server/node_modules/zwave-js/src/lib/node/Node.ts:715:14)
    at Function.handle (/home/keith/src/zwave-js/zwave-js-server/src/lib/node/message_handler.ts:25:36)
    at Object.node (/home/keith/src/zwave-js/zwave-js-server/src/lib/server.ts:54:26)
    at Client.receiveMessage (/home/keith/src/zwave-js/zwave-js-server/src/lib/server.ts:127:48)
    at WebSocket.<anonymous> (/home/keith/src/zwave-js/zwave-js-server/src/lib/server.ts:70:49)
    at WebSocket.emit (node:events:369:20) {
  code: 20,
  context: SendDataRequestTransmitReport {
    driver: [Driver],
    type: 0,
    functionType: 19,
    payload: <Buffer 04 01 02 b2 00 7f 7f 7f 7f 7f 00 01 06 00 00 00 00 42 06 00 00>,
    _callbackId: 4,
    _transmitStatus: 1
  },
  transactionSource: '    at Driver.sendMessage (/home/keith/src/zwave-js/zwave-js-server/node_modules/zwave-js/src/lib/driver/Driver.ts:2405:23)\n' +
    '    at Driver.sendCommand (/home/keith/src/zwave-js/zwave-js-server/node_modules/zwave-js/src/lib/driver/Driver.ts:2528:28)\n' +
    '    at ThermostatModeCCAPI.set (/home/keith/src/zwave-js/zwave-js-server/node_modules/zwave-js/src/lib/commandclass/ThermostatModeCC.ts:162:21)\n' +
    '    at Proxy.ThermostatModeCCAPI.<computed> (/home/keith/src/zwave-js/zwave-js-server/node_modules/zwave-js/src/lib/commandclass/ThermostatModeCC.ts:96:14)\n' +
    '    at ZWaveNode.setValue (/home/keith/src/zwave-js/zwave-js-server/node_modules/zwave-js/src/lib/node/Node.ts:715:14)\n' +
    '    at Function.handle (/home/keith/src/zwave-js/zwave-js-server/src/lib/node/message_handler.ts:25:36)\n' +
    '    at Object.node (/home/keith/src/zwave-js/zwave-js-server/src/lib/server.ts:54:26)\n' +
    '    at Client.receiveMessage (/home/keith/src/zwave-js/zwave-js-server/src/lib/server.ts:127:48)\n' +
    '    at WebSocket.<anonymous> (/home/keith/src/zwave-js/zwave-js-server/src/lib/server.ts:70:49)\n' +
    '    at WebSocket.emit (node:events:369:20)'
}
```
So I think it looks good.

Another thing I learned is that not all ZWaveErrors are handled the same way. At first I tried to set an invalid property
 with message:
```json
{
  "messageId": 1234,
  "command": "node.set_value",
  "nodeId": 7,
  "valueId": {
    "commandClass": 64,
    "endpoint": 1,
    "property": "test"
  },
  "value": 5
}
```

This resulted in an exception:
```
Error in driver ZWaveError: Thermostat Mode: "test" is not a supported property
    at Object.throwUnsupportedProperty (/home/keith/src/zwave-js/zwave-js-server/node_modules/zwave-js/src/lib/commandclass/API.ts:38:8)
    at Proxy.ThermostatModeCCAPI.<computed> (/home/keith/src/zwave-js/zwave-js-server/node_modules/zwave-js/src/lib/commandclass/ThermostatModeCC.ts:91:4)
    at ZWaveNode.setValue (/home/keith/src/zwave-js/zwave-js-server/node_modules/zwave-js/src/lib/node/Node.ts:715:14)
    at Function.handle (/home/keith/src/zwave-js/zwave-js-server/src/lib/node/message_handler.ts:25:36)
    at Object.node (/home/keith/src/zwave-js/zwave-js-server/src/lib/server.ts:54:26)
    at Client.receiveMessage (/home/keith/src/zwave-js/zwave-js-server/src/lib/server.ts:127:48)
    at WebSocket.<anonymous> (/home/keith/src/zwave-js/zwave-js-server/src/lib/server.ts:70:49)
    at WebSocket.emit (node:events:369:20)
    at WebSocket.emit (node:domain:470:12)
    at Receiver.receiverOnMessage (/home/keith/src/zwave-js/zwave-js-server/node_modules/ws/lib/websocket.js:835:20) {
  code: 36,
  context: undefined,
  transactionSource: undefined
}
```
but no error details from the server:
```json
{
    "type": "result",
    "success": true,
    "messageId": 1234,
    "result": {
        "success": false
    }
}
```

This is because for the `setValue` API, some ZWaveErrors are [handled](https://github.com/zwave-js/node-zwave-js/blob/41647cca42fd5ee5e5722ccf2097e85f5ba8181c/packages/zwave-js/src/lib/node/Node.ts#L772) in the driver, and a `error` event is emitted. The server currently just [logs this event](https://github.com/zwave-js/zwave-js-server/blob/0f17a037e4ed95273a0c48c10f909190fa2b2ecc/src/bin/server.ts#L63) to the console.

Is there anyway to return that error to the client? I'm not even sure how you would associate the emitted error with the corresponding client command.

**Comment by kpine** [comment]
Here's another error after it's been dead:
```json
{
    "type": "result",
    "success": false,
    "messageId": 1234,
    "errorCode": "zwave_error",
    "zwave_error_code": 18,
    "zwave_error_message": "The message cannot be sent because node 7 is dead"
}
```

**Comment by balloob** [comment]
ah I should update the casing. it should be zwaveErrorCode and zwaveErrorMessage.

**Comment by MartinHjelmare** [comment]
Looks good on a high level. 👍

**Pull request merged**
