### PR TITLE
Trim whitespaces from keys

### PR DESCRIPTION
**Pull request by raman325**
https://discord.com/channels/330944238910963714/800356888827002880/893171276645031977

### CODE REVIEW

**Comment by MartinHjelmare** [comment]
Was there a user that reported this issue?

**Comment by raman325** [comment]
No this just came from our discussion about stripping whitespaces

**Comment by MartinHjelmare** [comment]
Oh, I was thinking about stripping the `, 0x` from the OZW key.

**Comment by raman325** [comment]
got it, then this PR is unnecessary 👍🏾

**Pull request closed without merging**
