### PR TITLE
Catch the promises to stop unhandled promise rejection exception

### PR DESCRIPTION
**Pull request by marcus-j-davies**
Fixes https://github.com/zwave-js/zwave-js-server/issues/501

@raman325 
I see you are settling the promise' to do some mop up, So I have handled the rejection.
not really doing anything in here - but could log something if you prefer?

### CODE REVIEW

**Review by AlCalzone — CHANGES_REQUESTED** [review]
Unless there is a good reason not to (@raman325 ?), this should be removed:
https://github.com/zwave-js/zwave-js-server/blob/218f1bdb4aceea0f8fb83668893ef133c49d2a77/src/lib/controller/message_handler.ts#L279-L280

**Comment by raman325** [comment]
we create a deferred promise for both callbacks, shouldn't we reject them on abort?

**Comment by AlCalzone** [comment]
> shouldn't we reject them on abort

No, `abort` is called by the driver to let applications know that the process was aborted. There is no need to reject the promises to let the driver know - it already does.
Unless the server does some magic on abort that it needs the rejection for, I'd remove them.

**Comment by AlCalzone** [comment]
@raman325 to answer your question in the issue

The promises aren't meant to be rejected, compare the [documentation](https://zwave-js.github.io/node-zwave-js/#/api/controller?id=begininclusion):
> `grantSecurityClasses`:
> Instruct the application to display the user which security classes the device has requested and whether client-side authentication (CSA) is desired.
The returned promise **MUST resolve** to the user selection - which of the requested security classes have been granted and whether CSA was allowed.
If the user did not accept the requested security classes, the promise **MUST resolve** to `false`.

And likewise for `validateDSKAndEnterPIN`.

`abort` is
> Called by the driver when the user validation has timed out and needs to be aborted

---

The driver doesn't do anything with the promises when there was a timeout or after it aborted the secure inclusion. If the promises are rejected, it simply catches the error (and treats it as `false` if the callback was still active).

If HA means to abort the inclusion process, simply resolve to `false`.

**Comment by raman325** [comment]
I see, so then the PR should be to change the promises from aborting to resolving as `false` - @marcus-j-davies can you make the appropriate changes to this PR?

**Comment by AlCalzone** [comment]
@marcus-j-davies are you triggering this by canceling the user input?

**Comment by marcus-j-davies** [comment]
No,
I am not proving the Inclusion Grant allowing the timeout to trigger.

**Comment by AlCalzone** [comment]
Ok then the server should just leave these promises alone unless it needs them to be resolved or rejected.

**Comment by marcus-j-davies** [comment]
Are the promises internally settled by the driver when **abort** occurs?

the server is doing some cleanup on **finally**

**Comment by AlCalzone** [comment]
No it just silently ignores them. If the server relies on that cleanup, I'd probably resolve them to `false` here.

**Comment by marcus-j-davies** [comment]
Ok, I'll resolve them to false.

**Review by AlCalzone — APPROVED** [review]

**Review by raman325 — APPROVED** [review]

**Pull request merged**
